[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "annotate"
author = "Nicolas Kowenski"
author-email = "zakkg3@gmail.com"
classifiers = ["License :: OSI Approved :: MIT License"]
home-page = "https://github.com/zakkg3/podannotator"
